#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20, but for the 4th, 9th, and 17th iterations, displays bad luck from China, Japan, and Italy respectively.

counter=1
while [ $counter -le 20 ]
do
    echo $counter
    if [ $counter -eq 4 ]
    then
        echo "bad luck from China"
    elif [ $counter -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ $counter -eq 17 ]
    then
        echo "bad luck from Italy"
    fi

    ((counter++))
done
