#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20, but for the 4th, 9th, and 17th iterations, displays bad luck from China, Japan, and Italy respectively.

counter=1
while [ $counter -le 20 ]
do
    echo $counter
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((counter++))
done
