#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour = 1
minutes = 1

while [ $hour -le 12 ]
do
    while [ $minutes -le 59 ]
    do
        echo minutes
        ((minutes++))
    done
    echo "Hour: $hour"
    minutes = 1
    ((hour++))
done